#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Book_Library
{
    using System.Data.Linq;
    using System.Data.Linq.Mapping;
    using System.Data;
    using System.Collections.Generic;
    using System.Reflection;
    using System.Linq;
    using System.Linq.Expressions;
    using System.ComponentModel;
    using System;


    [global::System.Data.Linq.Mapping.DatabaseAttribute(Name = "elibraryDB")]
    public partial class DataClasses1DataContext : System.Data.Linq.DataContext
    {

        private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();

        #region Extensibility Method Definitions
        partial void OnCreated();
        partial void Insertbook_master_tbl(book_master_tbl instance);
        partial void Updatebook_master_tbl(book_master_tbl instance);
        partial void Deletebook_master_tbl(book_master_tbl instance);
        partial void Insertmember_master_tbl(member_master_tbl instance);
        partial void Updatemember_master_tbl(member_master_tbl instance);
        partial void Deletemember_master_tbl(member_master_tbl instance);
        #endregion

        public DataClasses1DataContext(string connection) :
                base(connection, mappingSource)
        {
            OnCreated();
        }

        public DataClasses1DataContext() :
            base(global::System.Configuration.ConfigurationManager.ConnectionStrings["elibraryDBConnectionString1"].ConnectionString, mappingSource)
        {
            OnCreated();
        }


        public DataClasses1DataContext(System.Data.IDbConnection connection) :
                base(connection, mappingSource)
        {
            OnCreated();
        }

        public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) :
                base(connection, mappingSource)
        {
            OnCreated();
        }

        public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) :
                base(connection, mappingSource)
        {
            OnCreated();
        }



        public System.Data.Linq.Table<book_master_tbl> book_master_tbls
        {
            get
            {
                return this.GetTable<book_master_tbl>();
            }
        }

        public System.Data.Linq.Table<member_master_tbl> member_master_tbls
        {
            get
            {
                return this.GetTable<member_master_tbl>();
            }
        }
    }

    [global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.book_master_tbl")]
    public partial class book_master_tbl : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

        private string _book_id;

        private string _book_name;

        private string _genre;

        private string _author_name;

        private string _publisher_name;

        private string _publish_date;

        private string _language;

        private string _eddition;

        private string _book_cost;

        private string _no_of_pages;

        private string _book_description;

        private string _actual_stock;

        private string _current_stock;

        private string _book_img_link;

        #region Extensibility Method Definitions
        partial void OnLoaded();
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        partial void OnCreated();
        partial void Onbook_idChanging(string value);
        partial void Onbook_idChanged();
        partial void Onbook_nameChanging(string value);
        partial void Onbook_nameChanged();
        partial void OngenreChanging(string value);
        partial void OngenreChanged();
        partial void Onauthor_nameChanging(string value);
        partial void Onauthor_nameChanged();
        partial void Onpublisher_nameChanging(string value);
        partial void Onpublisher_nameChanged();
        partial void Onpublish_dateChanging(string value);
        partial void Onpublish_dateChanged();
        partial void OnlanguageChanging(string value);
        partial void OnlanguageChanged();
        partial void OnedditionChanging(string value);
        partial void OnedditionChanged();
        partial void Onbook_costChanging(string value);
        partial void Onbook_costChanged();
        partial void Onno_of_pagesChanging(string value);
        partial void Onno_of_pagesChanged();
        partial void Onbook_descriptionChanging(string value);
        partial void Onbook_descriptionChanged();
        partial void Onactual_stockChanging(string value);
        partial void Onactual_stockChanged();
        partial void Oncurrent_stockChanging(string value);
        partial void Oncurrent_stockChanged();
        partial void Onbook_img_linkChanging(string value);
        partial void Onbook_img_linkChanged();
        #endregion

        public book_master_tbl()
        {
            OnCreated();
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_book_id", DbType = "NChar(10) NOT NULL", CanBeNull = false, IsPrimaryKey = true)]
        public string book_id
        {
            get
            {
                return this._book_id;
            }
            set
            {
                if ((this._book_id != value))
                {
                    this.Onbook_idChanging(value);
                    this.SendPropertyChanging();
                    this._book_id = value;
                    this.SendPropertyChanged("book_id");
                    this.Onbook_idChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_book_name", DbType = "NVarChar(MAX)")]
        public string book_name
        {
            get
            {
                return this._book_name;
            }
            set
            {
                if ((this._book_name != value))
                {
                    this.Onbook_nameChanging(value);
                    this.SendPropertyChanging();
                    this._book_name = value;
                    this.SendPropertyChanged("book_name");
                    this.Onbook_nameChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_genre", DbType = "NVarChar(MAX)")]
        public string genre
        {
            get
            {
                return this._genre;
            }
            set
            {
                if ((this._genre != value))
                {
                    this.OngenreChanging(value);
                    this.SendPropertyChanging();
                    this._genre = value;
                    this.SendPropertyChanged("genre");
                    this.OngenreChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_author_name", DbType = "NVarChar(MAX)")]
        public string author_name
        {
            get
            {
                return this._author_name;
            }
            set
            {
                if ((this._author_name != value))
                {
                    this.Onauthor_nameChanging(value);
                    this.SendPropertyChanging();
                    this._author_name = value;
                    this.SendPropertyChanged("author_name");
                    this.Onauthor_nameChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_publisher_name", DbType = "NVarChar(MAX)")]
        public string publisher_name
        {
            get
            {
                return this._publisher_name;
            }
            set
            {
                if ((this._publisher_name != value))
                {
                    this.Onpublisher_nameChanging(value);
                    this.SendPropertyChanging();
                    this._publisher_name = value;
                    this.SendPropertyChanged("publisher_name");
                    this.Onpublisher_nameChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_publish_date", DbType = "NVarChar(50)")]
        public string publish_date
        {
            get
            {
                return this._publish_date;
            }
            set
            {
                if ((this._publish_date != value))
                {
                    this.Onpublish_dateChanging(value);
                    this.SendPropertyChanging();
                    this._publish_date = value;
                    this.SendPropertyChanged("publish_date");
                    this.Onpublish_dateChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_language", DbType = "NVarChar(50)")]
        public string language
        {
            get
            {
                return this._language;
            }
            set
            {
                if ((this._language != value))
                {
                    this.OnlanguageChanging(value);
                    this.SendPropertyChanging();
                    this._language = value;
                    this.SendPropertyChanged("language");
                    this.OnlanguageChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_eddition", DbType = "NVarChar(MAX)")]
        public string eddition
        {
            get
            {
                return this._eddition;
            }
            set
            {
                if ((this._eddition != value))
                {
                    this.OnedditionChanging(value);
                    this.SendPropertyChanging();
                    this._eddition = value;
                    this.SendPropertyChanged("eddition");
                    this.OnedditionChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_book_cost", DbType = "NChar(10)")]
        public string book_cost
        {
            get
            {
                return this._book_cost;
            }
            set
            {
                if ((this._book_cost != value))
                {
                    this.Onbook_costChanging(value);
                    this.SendPropertyChanging();
                    this._book_cost = value;
                    this.SendPropertyChanged("book_cost");
                    this.Onbook_costChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_no_of_pages", DbType = "NChar(10)")]
        public string no_of_pages
        {
            get
            {
                return this._no_of_pages;
            }
            set
            {
                if ((this._no_of_pages != value))
                {
                    this.Onno_of_pagesChanging(value);
                    this.SendPropertyChanging();
                    this._no_of_pages = value;
                    this.SendPropertyChanged("no_of_pages");
                    this.Onno_of_pagesChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_book_description", DbType = "NVarChar(MAX)")]
        public string book_description
        {
            get
            {
                return this._book_description;
            }
            set
            {
                if ((this._book_description != value))
                {
                    this.Onbook_descriptionChanging(value);
                    this.SendPropertyChanging();
                    this._book_description = value;
                    this.SendPropertyChanged("book_description");
                    this.Onbook_descriptionChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_actual_stock", DbType = "NChar(10)")]
        public string actual_stock
        {
            get
            {
                return this._actual_stock;
            }
            set
            {
                if ((this._actual_stock != value))
                {
                    this.Onactual_stockChanging(value);
                    this.SendPropertyChanging();
                    this._actual_stock = value;
                    this.SendPropertyChanged("actual_stock");
                    this.Onactual_stockChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_current_stock", DbType = "NChar(10)")]
        public string current_stock
        {
            get
            {
                return this._current_stock;
            }
            set
            {
                if ((this._current_stock != value))
                {
                    this.Oncurrent_stockChanging(value);
                    this.SendPropertyChanging();
                    this._current_stock = value;
                    this.SendPropertyChanged("current_stock");
                    this.Oncurrent_stockChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_book_img_link", DbType = "NVarChar(MAX)")]
        public string book_img_link
        {
            get
            {
                return this._book_img_link;
            }
            set
            {
                if ((this._book_img_link != value))
                {
                    this.Onbook_img_linkChanging(value);
                    this.SendPropertyChanging();
                    this._book_img_link = value;
                    this.SendPropertyChanged("book_img_link");
                    this.Onbook_img_linkChanged();
                }
            }
        }

        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, emptyChangingEventArgs);
            }
        }

        protected virtual void SendPropertyChanged(String propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.member_master_tbl")]
    public partial class member_master_tbl : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

        private string _full_name;

        private string _dob;

        private string _contact_no;

        private string _email;

        private string _state;

        private string _city;

        private string _pincode;

        private string _full_address;

        private string _member_id;

        private string _password;

        private string _account_status;

        #region Extensibility Method Definitions
        partial void OnLoaded();
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        partial void OnCreated();
        partial void Onfull_nameChanging(string value);
        partial void Onfull_nameChanged();
        partial void OndobChanging(string value);
        partial void OndobChanged();
        partial void Oncontact_noChanging(string value);
        partial void Oncontact_noChanged();
        partial void OnemailChanging(string value);
        partial void OnemailChanged();
        partial void OnstateChanging(string value);
        partial void OnstateChanged();
        partial void OncityChanging(string value);
        partial void OncityChanged();
        partial void OnpincodeChanging(string value);
        partial void OnpincodeChanged();
        partial void Onfull_addressChanging(string value);
        partial void Onfull_addressChanged();
        partial void Onmember_idChanging(string value);
        partial void Onmember_idChanged();
        partial void OnpasswordChanging(string value);
        partial void OnpasswordChanged();
        partial void Onaccount_statusChanging(string value);
        partial void Onaccount_statusChanged();
        #endregion

        public member_master_tbl()
        {
            OnCreated();
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_full_name", DbType = "NVarChar(50)")]
        public string full_name
        {
            get
            {
                return this._full_name;
            }
            set
            {
                if ((this._full_name != value))
                {
                    this.Onfull_nameChanging(value);
                    this.SendPropertyChanging();
                    this._full_name = value;
                    this.SendPropertyChanged("full_name");
                    this.Onfull_nameChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_dob", DbType = "NVarChar(50)")]
        public string dob
        {
            get
            {
                return this._dob;
            }
            set
            {
                if ((this._dob != value))
                {
                    this.OndobChanging(value);
                    this.SendPropertyChanging();
                    this._dob = value;
                    this.SendPropertyChanged("dob");
                    this.OndobChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_contact_no", DbType = "NVarChar(50)")]
        public string contact_no
        {
            get
            {
                return this._contact_no;
            }
            set
            {
                if ((this._contact_no != value))
                {
                    this.Oncontact_noChanging(value);
                    this.SendPropertyChanging();
                    this._contact_no = value;
                    this.SendPropertyChanged("contact_no");
                    this.Oncontact_noChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_email", DbType = "NVarChar(50)")]
        public string email
        {
            get
            {
                return this._email;
            }
            set
            {
                if ((this._email != value))
                {
                    this.OnemailChanging(value);
                    this.SendPropertyChanging();
                    this._email = value;
                    this.SendPropertyChanged("email");
                    this.OnemailChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_state", DbType = "NVarChar(50)")]
        public string state
        {
            get
            {
                return this._state;
            }
            set
            {
                if ((this._state != value))
                {
                    this.OnstateChanging(value);
                    this.SendPropertyChanging();
                    this._state = value;
                    this.SendPropertyChanged("state");
                    this.OnstateChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_city", DbType = "NVarChar(50)")]
        public string city
        {
            get
            {
                return this._city;
            }
            set
            {
                if ((this._city != value))
                {
                    this.OncityChanging(value);
                    this.SendPropertyChanging();
                    this._city = value;
                    this.SendPropertyChanged("city");
                    this.OncityChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_pincode", DbType = "NVarChar(50)")]
        public string pincode
        {
            get
            {
                return this._pincode;
            }
            set
            {
                if ((this._pincode != value))
                {
                    this.OnpincodeChanging(value);
                    this.SendPropertyChanging();
                    this._pincode = value;
                    this.SendPropertyChanged("pincode");
                    this.OnpincodeChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_full_address", DbType = "NVarChar(MAX)")]
        public string full_address
        {
            get
            {
                return this._full_address;
            }
            set
            {
                if ((this._full_address != value))
                {
                    this.Onfull_addressChanging(value);
                    this.SendPropertyChanging();
                    this._full_address = value;
                    this.SendPropertyChanged("full_address");
                    this.Onfull_addressChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_member_id", DbType = "NVarChar(50) NOT NULL", CanBeNull = false, IsPrimaryKey = true)]
        public string member_id
        {
            get
            {
                return this._member_id;
            }
            set
            {
                if ((this._member_id != value))
                {
                    this.Onmember_idChanging(value);
                    this.SendPropertyChanging();
                    this._member_id = value;
                    this.SendPropertyChanged("member_id");
                    this.Onmember_idChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_password", DbType = "NVarChar(50)")]
        public string password
        {
            get
            {
                return this._password;
            }
            set
            {
                if ((this._password != value))
                {
                    this.OnpasswordChanging(value);
                    this.SendPropertyChanging();
                    this._password = value;
                    this.SendPropertyChanged("password");
                    this.OnpasswordChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_account_status", DbType = "NVarChar(50)")]
        public string account_status
        {
            get
            {
                return this._account_status;
            }
            set
            {
                if ((this._account_status != value))
                {
                    this.Onaccount_statusChanging(value);
                    this.SendPropertyChanging();
                    this._account_status = value;
                    this.SendPropertyChanged("account_status");
                    this.Onaccount_statusChanged();
                }
            }
        }

        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, emptyChangingEventArgs);
            }
        }

        protected virtual void SendPropertyChanged(String propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
#pragma warning restore 1591
